services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - user-service

networks:
  user-service:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  vault_data:
    driver: local